name: LastfmModern
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 0.1.0
    GENERATE_INFOPLIST_FILE: YES
    PRODUCT_BUNDLE_IDENTIFIER: fm.last.scrobbler.modern

targets:
  LastfmModern:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_NAME: LastfmModern
        INFOPLIST_KEY_CFBundleDisplayName: LastfmModern
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.music
        INFOPLIST_KEY_NSHumanReadableCopyright: Copyright (c) 2026

  LastfmModernTests:
    type: bundle.unit-test
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Tests
    dependencies:
      - target: LastfmModern
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: fm.last.scrobbler.modern.tests
